### ISSUE TITLE
咨询米家小鲸洗插件接口问题

### ISSUE THREAD

**Issue by springjk** [action-hong/my-template#1]
朋友你好，因为也找不到相关产品论坛或者官方网站，在米家 sdk 那边看到您是小鲸洗的开发，这边咨询一下问题：
购买的型号：xjx.toilet.relax
小鲸洗的产品为何没有在米家中实现开关盖的功能，这个功能只能遥控吗，还是说有相关接口，但是没有在米家实现？
如果有未在界面上实现的开关盖接口，我可以自己使用 homeassistant 中的 miot 进行 post 相关参数控制，是否有开关盖的接口？能否提供？

**Comment by action-hong** [comment]
1. 米家插件上没有实现
2. 该功能需要主控功能调整才能做

**Comment by springjk** [comment]
谢谢帮助
忘了阐述背景了：

贵司的这个开盖键位是在遥控器顶部，且是电容式触摸的，非按键触发，几个月实际使用过程中多次发现触发失败，（第一次点击无反应，第二次才有效，也就是有时候第一次按啥都没反应，第二次按键就正常，怀疑是什么休眠之类的，基本可以确认我是按到了，我还好，老人的话使用挺出戏的），所以希望知道一下细节：

1：那看起来如果厂家不更新主控的驱动应该就无法实现米家上的开关盖吧，也就是OTA 应该没有可能了吧
2：这遥控是蓝牙的还是射频？或许我可以自己想办法实现一个物理按键遥控按钮，有没有相关的参数帮助

**Comment by action-hong** [comment]
他们没有售后电话可以用吗?

具体硬件的内容我也不大清楚

我也不是他们公司的, 只是给他们做这个插件的

**Comment by springjk** [comment]
客服感觉也是外包的，一问三不知，也没法联系上技术，既然你们也是外包，那就打扰了，谢了。🤝

**Comment by bizshow** [comment]
我也遇到了和楼主一摸一样的问题，然后想来碰碰运气看能不能通过其他方式来实现自动开盖，看来是没戏了 😂
他们的遥控器不知道是什么协议，射频无法学习到，然后米家抓包也找不到相关miio的指令（可能固件里没有这个指令）
看来OTA也是指望不了了。。。
这个马桶，是奔着颜值去的，没想到功能这么不好用。。😂😂😂
